name: CI

on: ["push", "pull_request"]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: MBS version
        id: mbs_version
        run: |
          case $GITHUB_REF in
            refs/heads/main)
              export MBS_VERSION=latest
              ;;
            refs/heads/*)
              export MBS_VERSION=development
              ;;
            refs/tags/v*)
              export MBS_VERSION=${GITHUB_REF#refs/tags/v}
              ;;
          esac

          echo "##[set-output name=version;]$MBS_VERSION"

      - name: Build
        env:
          MBS_VERSION: ${{ steps.mbs_version.outputs.version }}
        run: |
          ./build.sh
          ./mbs.sh build run --verbose mbs

      - name: Push docker image
        if: ${{ steps.mbs_version.outputs.version != 'development' }}
        env:
          MBS_VERSION: ${{ steps.mbs_version.outputs.version }}
          DOCKER_IMAGE_REPO: visciang/mbs
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          DOCKER_IMAGE_TAG=$DOCKER_IMAGE_REPO:$MBS_VERSION

          echo "$DOCKERHUB_TOKEN" | docker login -u visciang --password-stdin
          docker push $DOCKER_IMAGE_TAG
