name: CI

on: ["push", "pull_request"]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build docker image
        run: |
          case $GITHUB_REF in
            refs/heads/*)
              MBS_VERSION=${GITHUB_REF#refs/heads/}
              ;;
            refs/tags/v*)
              MBS_VERSION=${GITHUB_REF#refs/tags/v}
              ;;
          esac

          ./build.sh

      - name: Build mbs in mbs
        run: |
          source ./mbs.sh
          ./mbs.sh build run --logs mbs

      - name: Push docker image
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          DOCKER_IMAGE_REPO: visciang/mbs
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          MBS_VERSION=${GITHUB_REF#refs/tags/v}
          DOCKER_IMAGE_TAG=$DOCKER_IMAGE_REPO:$MBS_VERSION

          echo "$DOCKERHUB_TOKEN" | docker login -u visciang --password-stdin
          docker tag mbs:latest $DOCKER_IMAGE_TAG
          docker push $DOCKER_IMAGE_TAG
