name: CI

on: ["push", "pull_request"]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build docker image
        run: |
          ./ci.sh

      - name: Build mbs in mbs
        run: |
          source ./mbs.sh
          ./mbs.sh build run --logs mbs

      - name: Push docker image
        if: github.ref == 'refs/heads/main'
        env:
          DOCKER_IMAGE_NAME: visciang/mbs:latest
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo "$DOCKERHUB_TOKEN" | docker login -u visciang --password-stdin
          docker tag mbs:latest $DOCKER_IMAGE_NAME
          docker push $DOCKER_IMAGE_NAME
